import os
import time
import subprocess

time.sleep(5)

# Go to the sett
# subprocess.run(['adb', 'shell', 'am', 'start', '-a', 'android.intent.action.VIEW', '-d', 'ovrapp",//ovrshell?section=studio'])

activities = [
        "com.android.settings.action.SUPPORT_SETTINGS",
        "android.settings.NETWORK_OPERATOR_SETTINGS",
        "com.android.settings.action.SETTINGS",
        "android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS",
        "android.settings.USER_SETTINGS",
        "android.settings.HOME_SETTINGS",
        "android.settings.DISPLAY_SETTINGS",
        "android.settings.DATA_SAVER_SETTINGS",
        "com.android.settings.BLUETOOTH_DEVICE_DETAIL_SETTINGS",
        "android.settings.LOCATION_SOURCE_SETTINGS",
        "android.settings.BLUETOOTH_SETTINGS",
        "android.settings.APPLICATION_DEVELOPMENT_SETTINGS",
        "android.settings.SETTINGS",
        "android.settings.HARD_KEYBOARD_SETTINGS",
        "android.settings.VR_LISTENER_SETTINGS",
        "android.settings.NOTIFICATION_POLICY_ACCESS_DETAIL_SETTINGS",
        "com.android.settings.sim.SIM_SUB_INFO_SETTINGS",
        "android.settings.ADD_ACCOUNT_SETTINGS",
        "android.settings.MANAGED_PROFILE_SETTINGS",
        "android.settings.USAGE_ACCESS_SETTINGS",
        "android.settings.PAIRING_SETTINGS",
        "android.settings.IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS",
        "com.android.settings.GLOBAL_ACTIONS_PANEL_SETTINGS",
        "com.android.settings.WIFI_TETHER_SETTINGS",
        "android.settings.NOTIFICATION_ASSISTANT_SETTINGS",
        "android.settings.ACTION_OTHER_SOUND_SETTINGS",
        "android.settings.ACCOUNT_SYNC_SETTINGS",
        "android.settings.LOCATION_SCANNING_SETTINGS",
        "android.settings.TETHER_SETTINGS",
        "android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS",
        "android.settings.SYSTEM_UPDATE_SETTINGS",
        "android.settings.INTERNAL_STORAGE_SETTINGS",
        "android.settings.MANAGE_APPLICATIONS_SETTINGS",
        "android.settings.SYNC_SETTINGS",
        "android.settings.QUICK_ACCESS_WALLET_SETTINGS",
        "android.settings.APP_OPS_SETTINGS",
        "android.settings.WEBVIEW_SETTINGS",
        "android.settings.NFC_PAYMENT_SETTINGS",
        "com.android.settings.TTS_SETTINGS",
        "android.settings.QUICK_LAUNCH_SETTINGS",
        "android.settings.MEMORY_CARD_SETTINGS",
        "android.settings.ACCESSIBILITY_SETTINGS",
        "android.settings.WIFI_CALLING_SETTINGS",
        "android.settings.DARK_THEME_SETTINGS",
        "android.settings.PRIVACY_SETTINGS",
        "com.android.settings.ADVANCED_CONNECTED_DEVICE_SETTINGS",
        "android.settings.ALL_APPS_NOTIFICATION_SETTINGS",
        "android.settings.STORAGE_VOLUME_ACCESS_SETTINGS",
        "android.settings.APPLICATION_DETAILS_SETTINGS",
        "android.settings.MANAGE_MORE_DEFAULT_APPS_SETTINGS",
        "android.settings.WIRELESS_SETTINGS",
        "android.settings.USER_DICTIONARY_SETTINGS",
        "android.settings.FOREGROUND_SERVICES_SETTINGS",
        "android.settings.NOTIFICATION_LISTENER_DETAIL_SETTINGS",
        "android.settings.WIFI_IP_SETTINGS",
        "android.settings.APPLICATION_SETTINGS",
        "android.settings.ACTION_DEVICE_CONTROLS_SETTINGS",
        "android.settings.ZEN_MODE_PRIORITY_SETTINGS",
        "android.net.vpn.SETTINGS",
        "android.settings.ZEN_MODE_AUTOMATION_SETTINGS",
        "android.settings.DEVICE_INFO_SETTINGS",
        "android.settings.FINGERPRINT_SETTINGS",
        "android.settings.SECURITY_SETTINGS",
        "android.settings.ZEN_MODE_SETTINGS",
        "android.settings.ZEN_MODE_EXTERNAL_RULE_SETTINGS",
        "android.settings.VPN_SETTINGS",
        "android.settings.BUGREPORT_HANDLER_SETTINGS",
        "android.settings.CONVERSATION_SETTINGS",
        "android.settings.MANAGE_ALL_APPLICATIONS_SETTINGS",
        "android.settings.ASSIST_GESTURE_SETTINGS",
        "android.settings.ENTERPRISE_PRIVACY_SETTINGS",
        "android.settings.WIFI_SETTINGS",
        "android.settings.APP_NOTIFICATION_SETTINGS",
        "android.settings.AIRPLANE_MODE_SETTINGS",
        "android.settings.SOUND_SETTINGS",
        "android.settings.VOICE_INPUT_SETTINGS",
        "android.settings.WIFI_SAVED_NETWORK_SETTINGS",
        "android.settings.DATA_ROAMING_SETTINGS",
        "android.settings.NFCSHARING_SETTINGS",
        "android.settings.ZEN_MODE_SCHEDULE_RULE_SETTINGS",
        "android.settings.NIGHT_DISPLAY_SETTINGS",
        "android.settings.ACCESSIBILITY_SETTINGS_FOR_SUW",
        "android.settings.ACTION_POWER_MENU_SETTINGS",
        "android.settings.NOTIFICATION_SETTINGS",
        "android.settings.DATA_USAGE_SETTINGS",
        "android.settings.DREAM_SETTINGS",
        "android.settings.action.MANAGE_WRITE_SETTINGS",
        "android.search.action.SEARCH_SETTINGS",
        "android.settings.INPUT_METHOD_SUBTYPE_SETTINGS",
        "android.settings.CAST_SETTINGS",
        "com.android.settings.ACCESSIBILITY_COLOR_SPACE_SETTINGS",
        "com.android.settings.APPLICATION_DEVELOPMENT_SETTINGS",
        "com.android.settings.APP_OPEN_BY_DEFAULT_SETTINGS",
        "android.settings.LOCATION_CONTROLLER_EXTRA_PACKAGE_SETTINGS",
        "android.settings.MANAGE_DEFAULT_APPS_SETTINGS",
        "com.android.settings.BATTERY_SAVER_SCHEDULE_SETTINGS",
        "android.settings.ACTION_PRINT_SETTINGS",
        "android.settings.INPUT_METHOD_SETTINGS",
        "com.android.settings.DISPLAY_SETTINGS",
        "android.settings.LOCALE_SETTINGS",
        "android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS",
        "android.settings.action.APP_USAGE_SETTINGS",
        "android.settings.APN_SETTINGS",
        "com.android.settings.action.IA_SETTINGS",
        "com.android.settings.SOUND_SETTINGS",
        "android.settings.CAPTIONING_SETTINGS",
        "android.settings.ZEN_MODE_EVENT_RULE_SETTINGS",
        "android.settings.APP_SEARCH_SETTINGS",
        "android.settings.FACE_SETTINGS",
        "android.settings.CHANNEL_NOTIFICATION_SETTINGS",
        "android.settings.ACTION_CONDITION_PROVIDER_SETTINGS",
        "android.settings.ACCESSIBILITY_DETAILS_SETTINGS",
        "android.settings.DATE_SETTINGS",
        "android.settings.BATTERY_SAVER_SETTINGS",
        "android.settings.PICTURE_IN_PICTURE_SETTINGS",
        "android.settings.ACTION_MEDIA_CONTROLS_SETTINGS",
        "android.settings.NFC_SETTINGS",
        "android.settings.STORAGE_MANAGER_SETTINGS",
        "android.settings.APP_NOTIFICATION_BUBBLE_SETTINGS",
]

startActivityCommand = "adb shell am start -a"

for activity in activities:
    os.system(startActivityCommand + activity)

    time.sleep(4)